### ISSUE TITLE
not displaying "Loss" status

### ISSUE THREAD

**Issue by Alchemistapf** [ANYbotics/gnome-shell-ping-monitor-applet#11]
The status on the status bar does not appear to show when the ping is lost - it displays the 'Bad' status instead.

Thanks for a really useful extension.

{
      "tag": "Open VPN",
      "name": "Open VPN",
      "address": "192.168.42.137",
      "ping_count": 2,
      "ping_interval": 0.5,
      "ping_deadline": 3,
      "refresh_interval": 5000,
      "active": true,
      "visible": true,
      "show_name": true,
      "show_address": true,
      "show_tooltip": true,
      "warning_threshold": 100
    }

![Screenshot from 2020-04-16 08-46-42](https://user-images.githubusercontent.com/13961212/79405649-2e455c00-7fbf-11ea-9340-17a5f55607ac.png)

![Screenshot from 2020-04-16 08-39-03](https://user-images.githubusercontent.com/13961212/79405365-68622e00-7fbe-11ea-9ada-c06d78e11f1f.png)

**Comment by samuelba** [comment]
Thanks for reporting this. I'll have a look what goes wrong here.

**Comment by samuelba** [comment]
The explanation is, that "Bad" is 100% packet loss and "Loss" is 0 < loss < 100%. The reason why I differentiated this was to show if no packets came through == Bad. I can name it differently if you like.

**Comment by Alchemistapf** [comment]
Thank you. The applet is fantastic.

Thanks again,

Alistair

*Dr Alistair Furze MChem Oxf; MPhil, PhD Manc; QTS Chest*
