### ISSUE TITLE
Ping update blocks gnome-shell UI

### ISSUE THREAD

**Issue by terencode** [ANYbotics/gnome-shell-ping-monitor-applet#2]
You can see that by continuously moving a window: it will freeze each time the extension start pinging again.

**Comment by samuelba** [comment]
You are right, I thought `GLib.spawn_async_with_pipes` runs in the background. I guess I have to somehow use threads for the pinging.

**Comment by samuelba** [comment]
It seems that mainly https://github.com/ANYbotics/gnome-shell-ping-monitor-applet/blob/24fb47cb0b4eb3d1973279abe8ab9d89dbf9c709/ping-monitor%40samuel.bachmann.gmail.com/extension.js#L904 is blocking the gnome-shell.

**Comment by terencode** [comment]
[This](https://github.com/xtranophilist/gnome-shell-extension-sensors/issues/16) might help you.

**Comment by samuelba** [comment]
Thank you for the hint. Commit https://github.com/ANYbotics/gnome-shell-ping-monitor-applet/commit/46448b905b0cbe28a62ac821069c514906768f42 should solve the problem.

**Comment by terencode** [comment]
I can confirm, thanks.
