### ISSUE TITLE
Zombie Bashes

### ISSUE THREAD

**Issue by SpyrosPsarras** [ANYbotics/gnome-shell-ping-monitor-applet#8]
Letting this run over 5hours, pc starts to hang because of the numerous bash shells it leaves as zombies.
The app works fine, but it does not kill the bash it used to make the ping request.
How to reproduce? open app and check the system-monitor for bashes. Every 2 seconds (or interval time), one (or more) bash terminals appears and sits there untill restart, waiting for some brain to eat (acting like a zombie).

**Comment by samuelba** [comment]
Thank you for reporting this. I will fix it.

**Comment by samuelba** [comment]
Should be fixed in commit https://github.com/ANYbotics/gnome-shell-ping-monitor-applet/commit/7867c89e831138b2fda37dfd10a07ccb659897cf
